### ISSUE TITLE
App won't even launch

### ISSUE THREAD

**Issue by v1n2e7t** [embraceplus/ios#1]
App won't launch i believe it is missing files

**Comment by iansane1** [comment]
Needs update to connect via Bluetooth to iOS 8.3 Apple devices

**Comment by v1n2e7t** [comment]
That is one of my goals along with brightness settings and the ability to disable lights with a toggleswitch but allow vibration (for movie theaters and such). As soon as working code is published i am going to dive into it with these ideas. It's missing a lot of required cocos2d i belive

**Comment by iansane1** [comment]
Did you have any luck?

**Comment by iansane1** [comment]
Did you have any luck?

**Comment by v1n2e7t** [comment]
yeah check out my fork

**Comment by v1n2e7t** [comment]
https://github.com/v1n2e7t/embrace-the-band

**Comment by iansane1** [comment]
Cool. I'm new to this site and how it works. Joined due to having two embrace+ bands that won't connect. How will the update be released for an iPhone?

**Comment by v1n2e7t** [comment]
Havent Gotten that far yet, i'll figure it out soon
